### ISSUE TITLE
Can't find new SMBIOS

### ISSUE THREAD

**Issue by sulthonuladib** [corpnewt/GenSMBIOS#12]
need new SMBIOS like iMac20,1

**Comment by lywnko** [comment]
need new SMBIOS like iMac20,1

**Comment by darionic** [comment]
I need it as well

**Comment by corpnewt** [comment]
Added in [this commit](https://github.com/corpnewt/GenSMBIOS/commit/b64354a1b29fb5af403dae931ae27d08c3715186) - note that there is no auto-built Linux version of macserial included in the OpenCorePkg releases, so GenSMBIOS will fall back on MacInfoPkg releases when run on Linux.

-CorpNewt

**Comment by sulthonuladib** [comment]
good improvements, thanks for that!! @corpnewt
