### ISSUE TITLE
Newest models are missing!   

### ISSUE THREAD

**Issue by ahadrox** [corpnewt/GenSMBIOS#14]
The new iMac20,1 and iMac20,2 code is missing. Please update.

**Comment by corpnewt** [comment]
Added in [this commit](https://github.com/corpnewt/GenSMBIOS/commit/b64354a1b29fb5af403dae931ae27d08c3715186) - note that there is no auto-built Linux version of macserial included in the OpenCorePkg releases, so GenSMBIOS will fall back on MacInfoPkg releases when run on Linux.

-CorpNewt
