### ISSUE TITLE
How this generates the serial numbers ??

### ISSUE THREAD

**Issue by Ram-Benz** [corpnewt/GenSMBIOS#16]
I tried one serial number {not from genbios} and it works {has invalid purachage date} ?So is there any formula to get other data 

Type = SystemProductName
Board Serial = MLB
SmUUID = SystemUUID

from it ?
Also can i use serial number of Mac pro when product name is imac ?

**Comment by corpnewt** [comment]
It leverages macserial from OpenCorePkg - info [here](https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/macserial/FORMAT.md).

-CorpNewt
