### ISSUE TITLE
No valid serial for iMac14,1

### ISSUE THREAD

**Issue by jericopulvera** [corpnewt/GenSMBIOS#2]
I've been trying around 100+ serial already an there is still no valid serial. any idea why?

**Comment by PepperoniDave** [comment]
Having same problem here. I can’t continue until I have a working SMBIOS/Serial.

**Comment by corpnewt** [comment]
Not an issue with this script as it only leverages acidanthera's [MacInfoPkg](https://github.com/acidanthera/MacInfoPkg).  If the serials generated are not valid - you'll want to post an issue on their bugtracker.

-CorpNewt
