### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by BlitzBolt24007** [corpnewt/GenSMBIOS#26]
idk if i am just stupid or what but, when i try to select a number for example 1, nothing happens. i have waited for it for about half of an hour. but still nothing happened
<img width="481" alt="Screenshot 2024-01-22 184305" src="https://github.com/corpnewt/GenSMBIOS/assets/61169756/4459473c-f2a1-4d06-b9d9-e7613e7c50bf">

**Comment by corpnewt** [comment]
Hmmm - I just verified here and it works as expected.  I wonder if there's some networking issue.  You can try downloading the [latest OpenCorePkg release](https://github.com/acidanthera/OpenCorePkg/releases/latest), extract the zip, and copy `macserial`, `macserial.exe`, and `macserial.linux` from OpenCore-X.Y.Z-RELEASE/Utilities/macserial to GenSMBIOS/Scripts and see if that bypasses the issue.

-CorpNewt

**Comment by BlitzBolt24007** [comment]
> Hmmm - I just verified here and it works as expected. I wonder if there's some networking issue. You can try downloading the [latest OpenCorePkg release](https://github.com/acidanthera/OpenCorePkg/releases/latest), extract the zip, and copy `macserial`, `macserial.exe`, and `macserial.linux` from OpenCore-X.Y.Z-RELEASE/Utilities/macserial to GenSMBIOS/Scripts and see if that bypasses the issue.
> 
> -CorpNewt

i dont have the GenSMBIOS/Scripts, how do i access it?

**Comment by corpnewt** [comment]
You should have it, it's a part of this repo: https://github.com/corpnewt/GenSMBIOS/tree/master/Scripts

-CorpNewt

**Comment by BlitzBolt24007** [comment]
i found it and ran it but still nothing happens
<img width="407" alt="Screenshot 2024-01-22 194901-99" src="https://github.com/corpnewt/GenSMBIOS/assets/61169756/bf496619-07e5-4058-9cac-6bafef20a80b">

**Comment by BlitzBolt24007** [comment]
nvm. i fixed it. thanks for the help. really useful.

**Comment by corpnewt** [comment]
What was the issue?

-CorpNewt

**Comment by BlitzBolt24007** [comment]
i was running the system in GIT bash. i should have been running it in the GenSMBIOS.bat. UGH... sorry about the trouble.

**Comment by corpnewt** [comment]
Ah - no worries!  Glad you got it figured out 👍 

-CorpNewt
