### ISSUE TITLE
Unable to Install/Update MacSerial

### ISSUE THREAD

**Issue by ndroftheline** [corpnewt/GenSMBIOS#3]
Hey corpnewt, thanks very much for the work you do on this tooling. 

I'm working with OpenCore on a common, inexpensive prebuilt from HP, a z230 workstation. Following https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/intel-config.plist/haswell#platforminfo - but I'm not clear that I've done this right. I've booted a Lubuntu 18.10 liveUSB and am running GenSMBIOS on the z230. This machine has internet connectivity (I just git cloned genSMBIOS to it) and I'm running an interactive sudo session in the live session, so I'm operating as root. 

I just ran GenSMBIOS, selected option 1, and got this output: 

```
  #######################################################
 #                 Getting MacSerial                   #
#######################################################

Gathering latest macserial info...
We ran into some problems :(

'linux2'

Cleaning up...

Done.

```

**Comment by corpnewt** [comment]
Can you try the code pushed in [this commit](https://github.com/corpnewt/GenSMBIOS/commit/8adf377c7113ed2e3474aa65c7f8fe24a1840d42) and see if that fixes the issue for you?  Seems `sys.platform` can be `linux`, `linux2`, or possibly even `linux3` - so I modified to to just check if it *starts* with `linux` and then normalizes.

-CorpNewt

**Comment by Dungeonseeker** [comment]
Same issue on a windows machine, slightly different error though

`Gathering latest macserial info...
We ran into some problems :(

'str' object has no attribute 'startsiwth'

Cleaning up...

Done.`

**Comment by Dungeonseeker** [comment]
Fixed by changing startsiwth to startswith on line 114

**Comment by corpnewt** [comment]
Hah - typo on my part.  Should be fixed [here](https://github.com/corpnewt/GenSMBIOS/commit/e0e79c5d88aa4492e81c588b1c1e67bc9eaca36b).  Sorry about that.

-CorpNewt
