### ISSUE TITLE
Macserials archieved, no longer updated.

### ISSUE THREAD

**Issue by mirahost** [corpnewt/GenSMBIOS#9]
Hello. It looks the the hardware database has moved here: https://github.com/acidanthera/OpenCorePkg/tree/master/AppleModels

**Comment by hrytskivr** [comment]
This is a very valid issue, I need to generate stuff for iMac20,2 and this thing can't do it ;(

**Comment by lywnko** [comment]
need new SMBIOS like iMac20,1

**Comment by corpnewt** [comment]
Added in [this commit](https://github.com/corpnewt/GenSMBIOS/commit/b64354a1b29fb5af403dae931ae27d08c3715186) - note that there is no auto-built Linux version of macserial included in the OpenCorePkg releases, so GenSMBIOS will fall back on MacInfoPkg releases when run on Linux.

-CorpNewt
